routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::resource('products', 'ProductController');

Route::resource('clients', 'ClientController');


Route::resource('invoices', 'InvoiceController');

Route::get('download/{id}', 'DownloadPDFController@download')->name("download");

Route::get('/', 'HomeController@index')->name("index");

app/Invoice.php
<?php

namespace App;

use App\Client;
use Illuminate\Database\Eloquent\Model;

class Invoice extends Model
{
    protected $fillable = [
        'id',
        'date',
        'amount',
        'term',
        'dueDate',
        'purchaseDate',
        'financePerc',
        'advanceAmt',
        'graceIntRate',
        'lateIntRate',
        'minPeriod',
        'minDate',
        'gracePeriod',
        'paymentDueDate',
        'defaultDue',
        'latePPeriod',
        'clientID',
    ];

    public $incrementing = false;

    protected $visible = [
        'id',
        'date',
        'amount',
        'term',
        'dueDate',
        'purchaseDate',
        'financePerc',
        'advanceAmt',
        'graceIntRate',
        'lateIntRate',
        'minPeriod',
        'minDate',
        'gracePeriod',
        'paymentDueDate',
        'defaultDue',
        'latePPeriod',
        'clientID',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
        'date',
        'dueDate',
        'minDate',
        'minDate',
        'paymentDueDate',
        'defaultDue',
        'purchaseDate'
    ];

    protected $primaryKey = 'id';

    public function client()
    {
        return $this->hasOne('App\Client', 'id', 'clientID');
    }

}

app/Http/Controllers/InvoiceController.php
<?php

namespace App\Http\Controllers;

use \Datetime;
use Schema;
use Redirect;
use DB;
use Illuminate\Support\Facades\Input;
use App\InterestCalculation;
use Carbon\Carbon;
use App\Invoice;
use App\Client;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;


class InvoiceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
        {
            $data['title'] = 'Invoices';
            $data['clients'] = Client::orderBy('id', 'asc')->get();

            $data['invoices'] = DB::table('invoices')
                ->join('clients', 'invoices.clientID', '=', 'clients.id')
                ->select('clients.id','clients.name','invoices.id','invoices.date','invoices.amount','invoices.dueDate','invoices.advanceAmt','invoices.paymentDueDate')
                ->paginate(10);
            return view('invoice.index',$data);
        }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['title'] = 'Create Invoice';
        $data['clients'] = Client::orderBy('id', 'asc')->get();
        return view('invoice.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validation = Validator::make($request->all(),[
            'id' => 'required|unique:invoices',
            'date' => 'required|date_format:d/m/Y',
            'amount' => 'required|numeric|max:1000000000',
            'term' => 'required|numeric|max:10000',
            'dueDate'=> 'required|date_format:d/m/Y',
            'purchaseDate'=>'required|date_format:d/m/Y',
            'financePerc' => 'required|numeric|max:100',
            'advanceAmt' => 'required|numeric|max:10000000',
            'graceIntRate' => 'required|numeric|max:100',
            'lateIntRate' => 'required|numeric|max:100',
            'minPeriod' => 'required|numeric|max:10000',
            'minDate' => 'required|date_format:d/m/Y',
            'gracePeriod' => 'required|numeric|max:1000',
            'paymentDueDate' => 'required|date_format:d/m/Y',
            'defaultDue' => 'required|date_format:d/m/Y',
            'latePPeriod' => 'required|numeric',
            'clientID' => 'required',
        ]);


        if ($validation->fails()) {
            return Redirect::back()
                ->withErrors($validation)
                ->withInput();
        }

        app('App\Http\Controllers\InterestCalculationController')->store($request);


        //get date from request
        $date1 = $request->get('dueDate');
        //add the converted date to request
        $request->request->add(['dueDate'=> DateTime::createFromFormat('m/d/Y', $date1)->getTimestamp()]);

        //get date from request
        $date1 = $request->get('purchaseDate');
        //add the converted date to request
        $request->request->add(['purchaseDate'=> DateTime::createFromFormat('m/d/Y', $date1)->getTimestamp()]);

        $date1 = $request->get('minDate');
        //add the converted date to request
        $request->request->add(['minDate'=> DateTime::createFromFormat('m/d/Y', $date1)->getTimestamp()]);

        $date1 = $request->get('paymentDueDate');
        //add the converted date to request
        $request->request->add(['paymentDueDate'=> DateTime::createFromFormat('m/d/Y', $date1)->getTimestamp()]);

        $date1 = $request->get('defaultDue');
        //add the converted date to request
        $request->request->add(['defaultDue'=> DateTime::createFromFormat('m/d/Y', $date1)->getTimestamp()]);

        $date1 = $request->get('date');
        //add the converted date to request
        $request->request->add(['date'=> DateTime::createFromFormat('m/d/Y', $date1)->getTimestamp()]);

        Invoice::create($request->all());

        return Redirect::to('invoices')
            ->with('success','Great! invoice created successfully.');


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
         $where = array('id' => $id);
         $data['invoice_info'] = invoice::where($where)->first();
         $data['title'] = 'View Invoice';
         $data['interestCalculations'] = DB::table('interest_calculations')
            ->join('invoices', 'interest_calculations.invoiceID', '=', 'invoices.id')
            ->select('interest_calculations.date',
                'interest_calculations.elaspeDay',
                'interest_calculations.id',
                'interest_calculations.date',
                'interest_calculations.amountDue',
                'interest_calculations.principal',
                'interest_calculations.minInterest',
                'interest_calculations.earlyInterest',
                'interest_calculations.lateInterest',
                'interest_calculations.totalCheck'
                )
             ->where('invoiceID','=',$id)
             ->orderBy('interest_calculations.date','asc')
             ->paginate(15);

         return view('invoice.view', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         $where = array('id' => $id);
         $data['invoice_info'] = invoice::where($where)->first();
         $data['title'] = 'Edit Invoice';
         $data['client'] = Client::where(array('id' => $data['invoice_info']->clientID))->first();


        return view('invoice.edit', $data);
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $validation = Validator::make($request->all(),[
            'date' => 'required|date_format:d/m/Y',
            'amount' => 'required|numeric|max:1000000000',
            'term' => 'required|numeric|max:10000',
            'dueDate'=> 'required|date_format:d/m/Y',
            'purchaseDate'=>'required|date_format:d/m/Y',
            'financePerc' => 'required|numeric',
            'advanceAmt' => 'required|numeric',
            'graceIntRate' => 'required|numeric',
            'lateIntRate' => 'required|numeric',
            'minPeriod' => 'required|numeric',
            'minDate' => 'required|date_format:d/m/Y',
            'gracePeriod' => 'required|numeric',
            'paymentDueDate' => 'required|date_format:d/m/Y',
            'defaultDue' => 'required|date_format:d/m/Y',
            'latePPeriod' => 'required|numeric',
        ]);

        if ($validation->fails()) {
            return Redirect::back()
                ->withErrors($validation)
                ->withInput();
        }

        Invoice::where('id',$id)->update(
            [
                "amount"=> $request->amount,
                "term" => $request->term,
                "dueDate" => Carbon::createFromFormat('d/m/Y',$request->dueDate)->format('Y-m-d H:i:s'),
                "purchaseDate" => Carbon::createFromFormat('d/m/Y',$request->purchaseDate)->format('Y-m-d H:i:s'),
                "financePerc" => $request->financePerc,
                "advanceAmt" => $request->advanceAmt,
                "graceIntRate" => $request->graceIntRate,
                "lateIntRate" => $request->lateIntRate,
                "minPeriod" => $request->minPeriod,
                "minDate" => Carbon::createFromFormat('d/m/Y',$request->minDate)->format('Y-m-d H:i:s'),
                "gracePeriod" => $request->gracePeriod,
                "paymentDueDate" => Carbon::createFromFormat('d/m/Y',$request->paymentDueDate)->format('Y-m-d H:i:s'),
                "defaultDue" => Carbon::createFromFormat('d/m/Y',$request->defaultDue)->format('Y-m-d H:i:s'),
                "latePPeriod" => $request-> latePPeriod,
                "date" => Carbon::createFromFormat('d/m/Y',$request->date)->format('Y-m-d H:i:s'),
            ]
        );


        InterestCalculation::where('invoiceID', $id)->delete();
        app('App\Http\Controllers\InterestCalculationController')->store($request);


        return Redirect::to('invoices')
       ->with('success','Great! Invoice updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         Invoice::where('id',$id)->delete();
         InterestCalculation::where('invoiceID', $id)->delete();

         return Redirect::to('invoices')->with('success','Invoice deleted successfully');
    }

}

resources/views/Invoice/create.blade.php
@extends('layouts.default')

@section('content')
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.css" rel="stylesheet">

<div class="buttonRow">
    <div class="text-right">
        <a href="{{ route('invoices.index') }}" class="btn btn-danger mb-2">Go Back</a>
    </div>
</div>
<hr />

<form action="{{ route('invoices.store') }}" method="POST" name="add_invoice">
    {{ csrf_field() }}
<div class="container">
  <div class="row">
    <div class="col">
      <div class="form-group">
          <strong>Debtor</strong>
          <select class="form-control" id="clientID" name="clientID">
              @foreach($clients as $client)
                <option value="{{$client->id}}">{{$client->name}}</option>
              @endforeach
          </select>
      </div>
      <div class="form-group">
          <strong>Invoice No</strong>
          <input type="text" name="id" class="form-control" placeholder="Enter Invoice No" value="{{ old('id') }}">
          <span class="text-danger">{{ $errors->first('id') }}</span>
      </div>
        <div class="form-group">
            <strong>Invoice Date</strong>
            <input type="text" id="date" class="form-control" name="date" placeholder="Enter Invoice Date" value="{{ old('date') }}">
            <span class="text-danger">{{ $errors->first('date') }}</span>
        </div>
        <script type="text/javascript">
            $( "#date" ).datepicker({
                dateFormat: "dd/mm/yy",
                onSelect: function() {
                    var date = jQuery("#date").val();
                    var term = jQuery("#term").val();
                    calculateDueDates(date,term);
                }
            })
        </script>

      <div class="form-group">
          <strong>Invoice Amount</strong>
          <input type="text" id="amount" name="amount" class="form-control" placeholder="Enter Invoice Amount" value="{{ old('amount') }}">
          <span class="text-danger">{{ $errors->first('amount') }}</span>
      </div>
        <div class="form-group">
          <strong>Invoice Term</strong>
          <input type="text" id="term" name="term" class="form-control" placeholder="Enter Invoice Term" value="{{ old('term') }}">
          <span class="text-danger">{{ $errors->first('term') }}</span>
      </div>
      <div class="form-group">
            <strong>Minimum period</strong>
            <input type="text" id="minPeriod" name="minPeriod" class="form-control" placeholder="Enter Minimum Period" value="{{ old('minPeriod') }}">
            <span class="text-danger">{{ $errors->first('minPeriod') }}</span>
      </div>
        <div class="form-group">
            <strong>Invoice Purchase Date</strong>
            <input type="text" id="purchaseDate" class="form-control" name="purchaseDate" placeholder="Enter Invoice Purchase Date" value="{{ old('purchaseDate') }}">
            <span class="text-danger">{{ $errors->first('purchaseDate') }}</span>
        </div>
        <script type="text/javascript">
            $('#purchaseDate').datepicker({
                dateFormat: "dd/mm/yy",
                onSelect: function() {
                    var date = jQuery("#purchaseDate").val();
                    calculateMinDate(date);
                }
            });
        </script>
      <div class="form-group">
              <strong>% Finance</strong>
              <input type="text" id="financePerc" name="financePerc" class="form-control" placeholder="Enter % Financed" value="{{ old('financePerc') }}">
              <span class="text-danger">{{ $errors->first('financePerc') }}</span>
        </div>
      <div class="form-group">
              <strong>Grace Interest Rate</strong>
              <input type="text" id="graceIntRate" name="graceIntRate" class="form-control" placeholder="Enter Grace Interest Rate" value="{{ old('graceIntRate') }}">
              <span class="text-danger">{{ $errors->first('graceIntRate') }}</span>
        </div>
      <div class="form-group">
              <strong>Late Interest Rate</strong>
              <input type="text" id="lateIntRate" name="lateIntRate" class="form-control" placeholder="Enter Late Interest Rate" value="{{ old('lateIntRate') }}">
              <span class="text-danger">{{ $errors->first('lateIntRate') }}</span>
        </div>
     <div class="form-group">
          <strong>Minimum Period</strong>
          <input type="text" id="minPeriod" name="minPeriod" class="form-control" placeholder="Enter Minimum Period" value="{{ old('minPeriod') }}">
          <span class="text-danger">{{ $errors->first('minPeriod') }}</span>
     </div>
     <div class="form-group">
           <strong>Buffer (Grace) Period</strong>
           <input type="text" id="gracePeriod" name="gracePeriod" class="form-control" placeholder="Enter Buffer (Grace) Period" value="{{ old('gracePeriod') }}">
           <span class="text-danger">{{ $errors->first('gracePeriod') }}</span>
      </div>
      <div class="form-group">
         <strong>Late Payment Period</strong>
         <input type="text" id="latePPeriod" name="latePPeriod" class="form-control" placeholder="Enter Late Payment Period" value="{{ old('latePPeriod') }}">
         <span class="text-danger">{{ $errors->first('latePPeriod') }}</span>
    </div>
    </div>
    <div class="col">
        <div class="invoiceContainer">
         <div class="row justify-content-center">
              <div>
              <p class="invoiceFieldText">Invoice Due Date:</p>
              </div>
              <div style="margin-left:15px">
              <input type="text" id="dueDate" name="dueDate" class="form-control" value="" readonly="readonly" value="{{ old('dueDate') }}">
              </div>
          </div>

         <div class="row justify-content-center">
              <div>
              <p class="invoiceFieldText">Advance Amount:</p>
              </div>
              <div style="margin-left:15px;">
              <input type="text" id="advanceAmt" name="advanceAmt" class="form-control" readonly="readonly" value="{{ old('advanceAmt') }}">
           </div>

         <div class="row justify-content-center">
            <div>
            <p class="invoiceFieldText">30 Days From Purchase (Min Date):</p>
            </div>
            <div style="margin-left:15px;">
            <input type="text" id="minDate" name="minDate" class="form-control" readonly="readonly" value="{{ old('minDate') }}">
            </div>
            </div>
        <div class="row justify-content-center">
            <div>
            <p class="invoiceFieldText">Payment Due Date:</p>
            </div>
            <div style="margin-left:15px;">
            <input type="text" id="paymentDueDate" name="paymentDueDate" class="form-control" readonly="readonly" value="{{ old('paymentDueDate') }}">
            </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div>
            <p class="invoiceFieldText">Default Due Date:</p>
            </div>
            <div style="margin-left:15px;">
            <input type="text" id="defaultDue" name="defaultDue" class="form-control" placeholder="Enter Address" value="27/5/2010" readonly="readonly" value="{{ old('defaultDue') }}">
            </div>
            </div>
        </div>
      </div>
  </div>
    <div class="row">
        <div class="col-md-12">
            <button type="submit" class="btn btn-primary">Create</button>
            <a href="{{ route('invoices.index') }}" class="btn btn-danger">Cancel</a>
        </div>
    </div>
</form>
@endsection

resources/views/Invoice/edit.blade.php
@extends('layouts.default')

@section('content')
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.css" rel="stylesheet">

<div class="buttonRow">
    <div class="text-right">
        <a href="{{ route('invoices.index') }}" class="btn btn-danger mb-2">Go Back</a>
    </div>
</div>
<hr />

<form action="{{ route('invoices.update', $invoice_info->id) }}" method="POST" name="update_invoice">
    @method('PATCH')
    {{ csrf_field() }}
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <strong>Debtor</strong>
                    <select class="form-control" id="clientID" name="clientID" disabled="disabled">
                        <option value="{{$invoice_info->clientID}}">{{$client->name}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <strong>Invoice No</strong>
                    <input type="text" name="id" class="form-control" value="{{$invoice_info->id}}" placeholder="Enter Invoice No" readonly="readonly">
                </div>
                <div class="form-group">
                    <strong>Invoice Date</strong>
                    <input type="text" id="date" class="form-control" value="{{date('d/m/Y', strtotime($invoice_info->date))}}" name="date" placeholder="Enter Invoice Date">
                    <span class="text-danger">{{ $errors->first('invoiceDate') }}</span>
                </div>
                <script type="text/javascript">
                    $( "#date" ).datepicker({
                        dateFormat: "dd/mm/yy",
                        onSelect: function() {
                            var date = jQuery("#date").val();
                            var term = jQuery("#term").val();
                            calculateDueDates(date,term);
                        }

                    })
                </script>
                <div class="form-group">
                    <strong>Invoice Amount</strong>
                    <input type="text" id="amount" value="{{ $invoice_info->amount}}" name="amount" class="form-control" placeholder="Enter Invoice Amount">
                    <span class="text-danger">{{ $errors->first('amount') }}</span>
                </div>
                <div class="form-group">
                    <strong>Invoice Term</strong>
                    <input type="text" id="term" value="{{ $invoice_info->term}}" name="term" class="form-control" placeholder="Enter Invoice Term">
                    <span class="text-danger">{{ $errors->first('term') }}</span>
                </div>
                <div class="form-group">
                    <strong>Minimum period</strong>
                    <input type="text" id="minPeriod" value="{{ $invoice_info->minPeriod}}" name="minPeriod" class="form-control" placeholder="Enter Minimum Period">
                    <span class="text-danger">{{ $errors->first('minPeriod') }}</span>
                </div>
                <div class="form-group">
                    <strong>Invoice Purchase Date</strong>
                    <input type="text" id="purchaseDate"  value="{{date('d/m/Y', strtotime($invoice_info->purchaseDate))}}"class="form-control" name="purchaseDate" placeholder="Enter Invoice Purchase Date">
                    <span class="text-danger">{{ $errors->first('purchaseDate') }}</span>
                </div>
                <script type="text/javascript">
                    $('#purchaseDate').datepicker({
                        dateFormat: "dd/mm/yy",
                        onSelect: function() {
                            var date = jQuery("#purchaseDate").val();
                            calculateMinDate(date);
                        }
                    });
                </script>
                <div class="form-group">
                    <strong>% Finance</strong>
                    <input type="text" id="financePerc" value="{{ $invoice_info->financePerc}}" name="financePerc" class="form-control" placeholder="Enter % Financed">
                    <span class="text-danger">{{ $errors->first('financePerc') }}</span>
                </div>
                <div class="form-group">
                    <strong>Grace Interest Rate</strong>
                    <input type="text" id="graceIntRate" value="{{ $invoice_info->graceIntRate}}" name="graceIntRate" class="form-control" placeholder="Enter Grace Interest Rate">
                    <span class="text-danger">{{ $errors->first('graceIntRate') }}</span>
                </div>
                <div class="form-group">
                    <strong>Late Interest Rate</strong>
                    <input type="text" id="lateIntRate" value="{{ $invoice_info->lateIntRate}}" name="lateIntRate" class="form-control" placeholder="Enter Late Interest Rate">
                    <span class="text-danger">{{ $errors->first('lateIntRate') }}</span>
                </div>
                <div class="form-group">
                    <strong>Minimum Period</strong>
                    <input type="text" id="minPeriod" value="{{ $invoice_info->minPeriod}}" name="minPeriod" class="form-control" placeholder="Enter Minimum Period">
                    <span class="text-danger">{{ $errors->first('minPeriod') }}</span>
                </div>
                <div class="form-group">
                    <strong>Buffer (Grace) Period</strong>
                    <input type="text" id="gracePeriod" value="{{ $invoice_info->gracePeriod}}" name="gracePeriod" class="form-control" placeholder="Enter Buffer (Grace) Period">
                    <span class="text-danger">{{ $errors->first('gracePeriod') }}</span>
                </div>
                <div class="form-group">
                    <strong>Late Payment Period</strong>
                    <input type="text" id="latePPeriod" value="{{ $invoice_info->latePPeriod}}" name="latePPeriod" class="form-control" placeholder="Enter Late Payment Period">
                    <span class="text-danger">{{ $errors->first('latePPeriod') }}</span>
                </div>
            </div>
            <div class="col">
                <div class="invoiceContainer">
                    <div class="row justify-content-center">
                        <div>
                            <p class="invoiceFieldText">Invoice Due Date:</p>
                        </div>
                        <div style="margin-left:15px">
                            <input type="text" id="dueDate"  value="{{date('d/m/Y', strtotime($invoice_info->dueDate))}}"name="dueDate" class="form-control" value="" readonly="readonly">
                        </div>
                    </div>

                    <div class="row justify-content-center">
                        <div>
                            <p class="invoiceFieldText">Advance Amount:</p>
                        </div>
                        <div style="margin-left:15px;">
                            <input type="text" id="advanceAmt" value="{{ $invoice_info->advanceAmt}} " name="advanceAmt" class="form-control" readonly="readonly">
                        </div>

                        <div class="row justify-content-center">
                            <div>
                                <p class="invoiceFieldText">30 Days From Purchase (Min Date):</p>
                            </div>
                            <div style="margin-left:15px;">
                                <input type="text" id="minDate" value="{{date('d/m/Y', strtotime($invoice_info->minDate))}}" name="minDate" class="form-control" readonly="readonly">
                            </div>
                        </div>
                        <div class="row justify-content-center">
                            <div>
                                <p class="invoiceFieldText">Payment Due Date:</p>
                            </div>
                            <div style="margin-left:15px;">
                                <input type="text" id="paymentDueDate" value="{{date('d/m/Y', strtotime($invoice_info->paymentDueDate))}}" name="paymentDueDate" class="form-control" readonly="readonly">
                            </div>
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div>
                            <p class="invoiceFieldText">Default Due Date:</p>
                        </div>
                        <div style="margin-left:15px;">
                            <input type="text" id="defaultDue" name="defaultDue" class="form-control" placeholder="Enter Address" value="{{date('d/m/Y', strtotime($invoice_info->defaultDue))}}" readonly="readonly">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <button type="submit" class="btn btn-primary">Update</button>
                <a href="{{ route('invoices.index') }}" class="btn btn-danger">Cancel</a>
            </div>
        </div>
</form>
@endsection

resources/views/Invoice/index.blade.php
@extends('layouts.default')

<div>
  @include('invoice.invoiceTable')
</div>

resources/views/Invoice/invoiceRecord.blade.php
<table class="table table-bordered invoiceRecord" id="laravel_crud">
    <thead>
    <tr>
        <th>Date</th>
        <th>Elasped Day</th>
        <th>Amount Due</th>

        <th>Principal Amount</th>
        <th>Minimum Interest</th>
        <th>Early Interest</th>
        <th>Late Interest</th>
        <th>Total Check</th>
    </tr>
    </thead>
    <tbody>
    @foreach($interestCalculations as $calculation)
    <tr>
        <td>{{ date('d/m/Y', strtotime($calculation->date)) }}</td>
        <td>{{ $calculation->elaspeDay }}</td>
        <td>{{ $calculation->amountDue }}</td>
        <td>{{ $calculation->principal }}</td>
        <td>{{ $calculation->minInterest }}</td>
        <td>{{ $calculation->earlyInterest }}</td>
        <td>{{ $calculation->lateInterest }}</td>
        <td>{{ $calculation->totalCheck }}</td>
    </tr>

    @endforeach
    </tbody>
</table>
<div style="display:flex;justify-content:center">
{{$interestCalculations ->links()}}
</div>

resources/views/Invoice/invoiceTable.blade.php
@section('content')
<div>
 <div class="buttonRow">
    <a href="{{ route('invoices.create')}}" class="btn btn-success mb-2">Add</a>
 </div>

  <div class="">
      <table class="table table-bordered" id="laravel_crud">
      <thead>
      <tr>
          <th>Id</th>
          <th>Date</th>
          <th>Client Name</th>

          <th>Amount</th>
          <th>Due Date</th>
          <th>Advance Amount</th>
          <th>Payment Due Date</th>
          <th colspan="2" class="text-center">Action</th>
      </tr>
      </thead>
      <tbody>
      @foreach($invoices as $invoice)
      <tr>
          <td>{{ $invoice->id }}</td>
          <td>{{ date('d/m/Y', strtotime($invoice->date)) }}</td>
          <td>{{ $invoice->name }}</td>
          <td>{{ $invoice->amount }}</td>
          <td>{{ date('d/m/Y', strtotime($invoice->dueDate)) }}</td>
          <td>{{ $invoice->advanceAmt }}</td>
          <td>{{ date('d/m/Y', strtotime($invoice->paymentDueDate)) }}</td>
          <td class="">
              <div>
                  <a href="{{ route('invoices.show',$invoice->id)}}" style="display:inline-block" class="btn btn-primary">View</a>
                  <a href="{{ route('invoices.edit',$invoice->id)}}" style="display:inline-block" class="btn btn-primary">Edit</a>
                  <form action="{{ route('invoices.destroy', $invoice->id)}}" style="display:inline-block"  method="post">
                      {{ csrf_field() }}
                      @method('DELETE')
                      <button class="btn btn-danger" type="submit">Delete</button>
                  </form>
              </div>
          </td>
      </tr>
      @endforeach
      @if(count($invoices) < 1)
      <tr>
          <td colspan="10" class="text-center">There are no invoice available yet!</td>
          </td>
      </tr>
      @endif
      </tbody>
      </table>
      <div style="display:flex;justify-content:center">
          {{$invoices ->links()}}
      </div>
  </div>
    @endsection

resources/views/Invoice/view.blade.php
@extends('layouts.default')

@section('content')
<div>
    <div class="buttonRow">
        <a href="{{ route('invoices.edit',$invoice_info->id)}}" style="display:inline-block" class="btn btn-primary">Edit</a>
        <a href="" style="display:inline-block" class="btn btn-primary">Export to Document</a>

    </div>

    <div class="container">
        @include('invoice.invoiceDetailTable')

</div>
<div>
    <h4>Interest Calculation</h4>
    @include('invoice.invoiceRecord')
</div>
    <div style="padding-top: 20%"></div>
@endsection