routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::resource('products', 'ProductController');

Route::resource('clients', 'ClientController');


Route::resource('invoices', 'InvoiceController');

Route::get('download/{id}', 'DownloadPDFController@download')->name("download");

Route::get('/', 'HomeController@index')->name("index");

app/Client.php
<?php
 namespace App;
 use Illuminate\Database\Eloquent\Model;
 class Client extends Model
 {
    protected $fillable = [
     'name',
     'address',
        'postalCode',
    ];

     protected $visible = ['name', 'address'];

     protected $primaryKey = 'id';
 }

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use Redirect;
use App\Client;
use Illuminate\Http\Request;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
        {
            $data['clients'] = Client::orderBy('id','desc')->paginate(10);
            $data['title'] = 'Clients';

            return view('client.index',$data);
        }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
        {
            $data['title'] = 'Add Client';
            return view('client.create', $data);
        }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'address' => 'required',
            'postalCode' => 'required',
        ]);

        Client::create($request->all());

        return Redirect::to('clients')
       ->with('success','Great! Client created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
         $where = array('id' => $id);
         $data['client'] = Client::where($where)->first();

         return view('client.edit', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         $where = array('id' => $id);
         $data['client_info'] = Client::where($where)->first();
         $data['title'] = 'Edit Client';

         return view('client.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $request->validate([
            'name' => 'required',
            'address' => 'required',
             'postalCode' => 'postalCode',
        ]);

        $update = ['name' => $request->name, 'address' => $request->address];
        Client::where('id',$id)->update($update);

        return Redirect::to('clients')
       ->with('success','Great! Client updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         Client::where('id',$id)->delete();

         return Redirect::to('clients')->with('success','Client deleted successfully');
    }
}

resources/views/Client/clientTable.blade.php
@section('content')

 <div class="buttonRow">
    <a href="{{ route('clients.create')}}" class="btn btn-success mb-2">Add</a>
 </div>

  <div class="">
    <table class="table table-bordered" id="laravel_crud">
     <thead>
        <tr>
           <th>Id</th>
           <th>Name</th>
            <th>Postal Code</th>
           <th>Address</th>
           <th colspan="1" class="text-center">Action</th>
        </tr>
     </thead>
     <tbody>
        @foreach($clients as $client)
        <tr>
           <td>{{ $client->id }}</td>
           <td>{{ $client->name }}</td>
            <td>{{ $client->postalCode }}</td>
           <td>{{ $client->address }}</td>
           <td class="">
           <div>
            <a href="{{ route('clients.edit',$client->id)}}" style="display:inline-block" class="btn btn-primary">Edit</a>
           <form action="{{ route('clients.destroy', $client->id)}}" style="display:inline-block"  method="post">
            {{ csrf_field() }}
            @method('DELETE')
            <button class="btn btn-danger" type="submit">Delete</button>
          </form>
          </div>
          </td>
        </tr>
        @endforeach

        @if(count($clients) < 1)
          <tr>
           <td colspan="10" class="text-center">There are no client available yet!</td>
          </td>
        </tr>
        @endif
     </tbody>
    </table>
      <div style="display:flex;justify-content:center">
          {{$clients ->links()}}
      </div>
</div>
 @endsection

resources/views/Client/create.blade.php
@extends('layouts.default')

@section('content')
<div class="buttonRow">
    <div class="text-right">
        <a href="{{ route('clients.index') }}" class="btn btn-danger mb-2">Go Back</a>
    </div>
</div>
<hr />

<form action="{{ route('clients.store') }}" method="POST" name="add_client">
    {{ csrf_field() }}

    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <strong>Name</strong>
                <input type="text" name="name" class="form-control" placeholder="Enter name">
                <span class="text-danger">{{ $errors->first('name') }}</span>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <strong>Postal Code</strong>
                <input type="text" name="postalCode" class="form-control" placeholder="Enter Postal Code">
                <span class="text-danger">{{ $errors->first('postalCode') }}</span>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <strong>Address</strong>
                <input type="text" name="address" class="form-control" placeholder="Enter Address">
                <span class="text-danger">{{ $errors->first('address') }}</span>
            </div>
        </div>

        <div class="col-md-12">
            <button type="submit" class="btn btn-primary">Create</button>
            <a href="{{ route('clients.index') }}" class="btn btn-danger">Cancel</a>
        </div>
    </div>
</form>
@endsection

resources/views/Client/edit.blade.php
@extends('layouts.default')

@section('content')

<div class="buttonRow">
    <div class="text-right">
        <a href="{{ route('clients.index') }}" class="btn btn-danger mb-2">Go Back</a>
    </div>
</div>
<hr />

<form action="{{ route('clients.update', $client_info->id) }}" method="POST" name="update_product">
  {{ csrf_field() }}
  @method('PATCH')

  <div class="row">
      <div class="col-md-12">
          <div class="form-group">
              <strong>Name</strong>
              <input type="text" name="name" class="form-control" placeholder="Enter Title" value="{{ $client_info->name }}">
              <span class="text-danger">{{ $errors->first('name') }}</span>
          </div>
      </div>
      <div class="col-md-12">
          <div class="form-group">
              <strong>Postal Code</strong>
              <input type="text" name="address" class="form-control" placeholder="Enter Postal Code" value="{{ $client_info->postalCode }}">
              <span class="text-danger">{{ $errors->first('postalCode') }}</span>
          </div>
      </div>
      <div class="col-md-12">
                <div class="form-group">
                    <strong>Address</strong>
                    <input type="text" name="address" class="form-control" placeholder="Enter Address" value="{{ $client_info->address }}">
                    <span class="text-danger">{{ $errors->first('address') }}</span>
                </div>
            </div>
      <div class="col-md-12">
          <button type="submit" class="btn btn-primary">Submit</button>
          <a href="{{ route('clients.index') }}" class="btn btn-danger">Cancel</a>
      </div>
  </div>

</form>
@endsection

resources/views/Client/index.blade.php
@extends('layouts.default')

<div>
  @include('client.clientTable')
</div>